#!/bin/bash

read -p "please input your IP last number : " i

ping -c 4 192.168.163.$i 1>/dev/null 2>&1

if [ $? -eq 0 ]
then 
    echo "The IP address is alredy set, please set another one."
    exit 1
else
    cat > /etc/sysconfig/network-scripts/ifcfg-ens33 <<EOF
TYPE=Ethernet
BOOTPROTO=static
NAME=ens33
DEVICE=ens33
IPADDR="192.168.163.$i"
GATEWAY=192.168.163.2
ONBOOT=yes
EOF

ifdown ens33
ifup ens33
fi
